apls/books/urls.py
from django.urls import path

from apls.books import views


app_name = 'book'

urlpatterns = [
    path('', views.book_index, name='index'),
    path('libro/<slug:slug>/', views.detail_view, name='detail'),
]

apls/carts/urls.py
from django.urls import path

from apls.carts import views

app_name = 'cart'

urlpatterns = [
	path('carrito/', views.cart_view, name="detail"),
	path('add_item/', views.add_item_view, name="add_item"),
]

store/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('apls.users.urls')),
    path('', include('apls.books.urls')),
    path('', include('apls.carts.urls')),
    path('', include('apls.orders.urls')),
    path('admin/', admin.site.urls),
]

from django.conf import settings
from django.conf.urls.static import static

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apls/books/models.py
import uuid

from django.db import models
from django.urls import reverse
from django.template.defaultfilters import slugify



# Models
class Editorial(models.Model):
	name = models.CharField(max_length=120)

	def __str__(self):
		return self.name



class Author(models.Model):
	name = models.CharField(max_length=120)
	country = models.CharField(max_length=80)

	def __str__(self):
		return self.name



class Book(models.Model):

	LENGUAGE = (
		('es', 'Español'),
		('en', 'Ingles'),
	)

	BINDING = (
		('TN', 'Tapa normal'),
		('TP', 'Tapa dura'),
	)

	id_uuid = models.CharField(default=uuid.uuid4, max_length=36, editable=False)
	slug = models.SlugField(unique=True, editable=False)
	name = models.CharField(max_length=120)
	description = models.TextField()
	image = models.ImageField(upload_to='books/')
	page_numbers = models.PositiveIntegerField(default=0)
	year_publication = models.DateField(null=True, blank=True)
	lenguage = models.CharField(max_length=2, choices=LENGUAGE, default='es')
	book_binding = models.CharField(max_length=2, choices=BINDING, default='TN')
	price = models.DecimalField(max_digits=6, decimal_places=2, default=0.00)
	stock = models.PositiveIntegerField(default=0)

	author = models.ForeignKey(Author, on_delete=models.CASCADE, related_name='books')
	editorials = models.ManyToManyField(Editorial, related_name='books')

	def __str__(self):
		return self.name

	def get_editorials(self):
		return ', '.join([editorial.name for editorial in self.editorials.all()])
		
	def save(self, *args, **kwargs):
		if not self.id:
			self.slug = slugify(self.name) + '-' +  str(uuid.uuid4()).split('-')[0]
		super(Book, self).save(*args, **kwargs)

apls/books/views.py
# Django
from django.shortcuts import render
from django.shortcuts import get_object_or_404

# Models
from apls.books.models import Book


def book_index(request):
	books = Book.objects.all()
	ctx = {
		'books': books
	}
	return render(request, 'books/index_book.html', ctx)



def detail_view(request, slug):
	book = get_object_or_404(Book, slug=slug)
	return render(request, 'books/detail.html', {'book': book})

apls/books/templates/books/detail.html
{% extends 'base.html' %}

{% block title %}{{ book.name }} | BookStore{% endblock %}


{% block content %}
<section class="section-detail">
	<div class="container-detail">
		<div class="gallery">
			<img class="img-fluid" src="{{ book.image.url }}">
		</div>
		<div class="book-detail">
			<p class="book-detail-name">{{ book.name }}</p>
			<p>Author: <span class="book-detail-author">{{ book.author }}</span> | Editorial: <span class="book-detail-author">{{ book.get_editorials }}</span></p>
			<p class="book-detail-price">$ 199.99</p>
			<div class="book-detail-info">
				<p>Información</p>
				<p class="book-info">{{ book.description }}</p>
			</div>
			<form action="{% url 'cart:add_item' %}" method="post">
				{% csrf_token %}
				<input type="hidden" name="book_id" value="{{ book.id_uuid }}">
				<input type="number" name="quantity" value="1">
				<button class="btn is-link" type="submit">Añadir a carrito</button>
			</form>
		</div>
	</div>
	{% if messages %}
	<ul class="messages">
	    {% for message in messages %}
	    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
	    {% endfor %}
	</ul>
	{% endif %}
</section>
{% endblock %}

apls/books/templates/books/index_book.html
{% extends 'base.html' %}

{% block title %}Book Store{% endblock %}


{% block content %}
<section>
	<h1 class="h1">Libros en Book Store</h1>

	<div class="container-section">
	{% for book in books %}
		<article>
			<img class="img-fluid" src="{{ book.image.url }}">
			<p class="book-type">{{ book.get_book_binding_display }}l</p>
			<a href="{% url 'book:detail' book.slug %}" class="book-name"><p>{{ book.name }}</p></a>
			<p class="book-author">{{ book.author }}</p>
			<p class="book-price">$ {{ book.price }}</p>
			<a href="#" class="btn-add-cart">Añadir a carrito</a>
		</article>
	{% endfor %}
	</div>
</section>

{% endblock %}