apls/carts/urls.py
from django.urls import path

from apls.carts import views

app_name = 'cart'

urlpatterns = [
	path('carrito/', views.cart_view, name="detail"),
	path('add_item/', views.add_item_view, name="add_item"),
]

apls/orders/urls.py
from django.urls import path

from apls.orders import views

app_name = 'order'

urlpatterns = [	
	path('orden/', views.order_view, name="detail"),
	path('orden/confirm/<uuid:id_uuid>/', views.confirm_order, name='confirm'),
]

store/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('apls.users.urls')),
    path('', include('apls.books.urls')),
    path('', include('apls.carts.urls')),
    path('', include('apls.orders.urls')),
    path('admin/', admin.site.urls),
]

from django.conf import settings
from django.conf.urls.static import static

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apls/carts/models.py
import uuid
from django.conf import settings
from django.db import models

# Create your models here.
from apls.books.models import Book


class Cart(models.Model):

	STATUS = (
		('CR', 'CREATED'),
		('CA', 'CANCELED'),
		('CO', 'COMPLETED'),
	)

	id_uuid = models.CharField(default=uuid.uuid4, max_length=36, editable=False)
	user = models.ForeignKey(
		settings.AUTH_USER_MODEL, related_name='carts',
		on_delete= models.CASCADE, null=True, blank=True
	)
	subtotal = models.DecimalField(max_digits=8, decimal_places=2, default=0.0)
	total = models.DecimalField(max_digits=8, decimal_places=2, default=0.0)
	status = models.CharField(max_length=2, choices=STATUS, default='CR')
	created = models.DateTimeField(auto_now_add=True)

	def __str__(self):
		"""Return owner's cart."""
		return f'Cart of {self.user if self.user else self.id_uuid}'

	def qty_items(self):
		return sum([obj.quantity for obj in self.cart_items.all()])

	def update_total(self):
		self.total = sum([obj.total for obj in self.cart_items.all()])
		self.save()

	def completed(self):
		self.status = 'CO'
		self.save()



class CartItem(models.Model):
	id_uuid = models.CharField(default=uuid.uuid4, max_length=36, editable=False)
	book = models.ForeignKey(Book, related_name='cart_items', on_delete=models.CASCADE)
	cart = models.ForeignKey(Cart, related_name='cart_items', on_delete=models.CASCADE)
	price = models.DecimalField(max_digits=6, decimal_places=2, default=0.00)
	quantity = models.PositiveIntegerField(default=1)
	created = models.DateTimeField(auto_now_add=True)

	def __str__(self):
		"""Return username."""
		return f'Qty: {self.quantity} - {self.book.name}'

	@property
	def total(self):
		return self.price * self.quantity

apls/carts/views.py
# Django
from django.contrib import messages
from django.shortcuts import render, redirect

# Models
from apls.books.models import Book
from apls.carts.models import Cart, CartItem


# Function Views
def cart_view(request):
	return render(request, 'carts/cart.html', {})


def add_item_view(request):
	if request.user.is_authenticated:
		user = request.user
	else:
		user = None

	id_uuid = request.session.get('cart_id')

	cart = Cart.objects.filter(id_uuid=id_uuid).first()

	if cart is None:
		cart = Cart.objects.create(user=user)

	request.session['cart_id'] = str(cart.id_uuid)

	if request.method == "POST" and cart:
		book_id = request.POST.get('book_id')
		quantity = request.POST.get('quantity')

		book = Book.objects.filter(id_uuid=book_id).first()

		cart_item = CartItem.objects.filter(cart=cart, book=book).first()

		if cart_item:
			cart_item.quantity += int(quantity)
			cart_item.save()
		else:
			CartItem.objects.create(
				book=book, cart=cart,
				quantity=quantity, price=book.price
			)

		cart.update_total()

		messages.info(request, f'Se ha añadido {quantity} libro de la {book.name}')

		return redirect('book:detail', book.slug)

	return render(request, 'books/detail.html', {'book': book})

apls/carts/templates/carts/cart.html
{% extends 'base.html' %}
{% load humanize %}

{% block title %}Carrito | BookStore{% endblock %}

{% block css %}
<link rel="stylesheet" href="https://unpkg.com/bulma@0.9.0/css/bulma.min.css" />
{% endblock %}


{% block content %}
<section class="section-detail">
{% if pending_cart %}
  <table class="table table-full" style="width: 100%; margin-top: 20px;">
    <thead>
      <tr>
        <th><abbr title="Position">#</abbr></th>
        <th>Libros</th>
        <th>Cantidad</th>
        <th>Precio</th>
        <th style="text-align: right;">Total</th>        
      </tr>
    </thead>
    <tbody>
      {% for item in pending_cart.cart_items.all %}
      <tr>
        <th>{{ forloop.counter }}</th>
        <td>{{ item.book.name }}</td>
        <td>{{ item.quantity }}</td>
        <td>$ {{ item.price|intcomma }}</td>
        <td style="text-align: right;"><strong>$ {{ item.total|intcomma }}</strong></td>
      </tr>        
      {% endfor %}
    </tbody>
  </table>
  <div class="cart-total">
    <p>Total: <strong>$ {{ pending_cart.total|intcomma }}</strong></p>
  </div>

  <div class="cart-total" style="margin-top: 20px">
    <a href="#" class="button" style="margin-right: 16px">Vaciar carrito</a>
    <a href="{% url 'order:detail' %}" class="button is-info">Realizar pago</a>
  </div>

{% else %}
  <div class="empty-cart">
    <h2>Carrito Vacío</h2>    
  </div>
{% endif %}
</section>
{% endblock %}

apls/carts/templates/carts/confirm.html
{% extends 'base.html' %}
{% load humanize %}

{% block title %}Confirmar pedido | BookStore{% endblock %}

{% block css %}
<link rel="stylesheet" href="https://unpkg.com/bulma@0.9.0/css/bulma.min.css" />
{% endblock %}


{% block content %}
<div class="section-detail orders">
  <!-- S H O W   T O T A L -->
  <div class="display_total">
    <p class="display_total-title">Resumen de compra</p>
    <hr class="display_total-hr">
    <div class="display_values">
      <p>Productos (2)</p>
      <p>$ 200</p>
    </div>
    <div class="display_values">
      <p>Envío</p>
      <p>$ 100</p>
    </div>
    <hr class="display_total-hr">
    <div class="display_values">
      <p>Total</p>
      <p>$ 300</p>
    </div>
    <div class="mt-24">
      <a href="#" class="button is-success is-fullwidth">Confirmar</a>      
    </div>
  </div>
  <!-- END: S H O W   T O T A L -->

  <!-- S H I P P I N G   A D D R E S S -->
  <div class="content_order">

    <p class="address_text">Confirma tu pedido</p>

    <div class="card">
      <div class="card-body">
        <div class="row">
          <!-- Address Detail -->
          <div class="col-4">
            <div class="font-weight-bold">
              <strong>Calle 50 entre 23 y 25</strong>
            </div>
            <div class="card-text">
              C.P.: <strong>24100</strong>
            </div>
            <div class="cart-text">
              {{ shipping_address.get_name }}
            </div>
            <div class="cart-text">
              Referencia: Frente una casa
            </div>
            <div class="card-text">
              <p>Nombre del comprador - (938) 123 4567</p>  
            </div>
          </div>
          <br>
          <!-- END: Address Detail -->
          <!-- Card Detail -->
          <div class="col-4">
            <div class="font-weight-bold">
              Método de pago
            </div>
            <div class="card-text">
              Tarjeta terminación 0000
            </div>
          </div>
          <br>
          <!-- END: Card Detail -->
          <!-- Promo Detail -->
          <div class="col-4">
            <div class="font-weight-bold">
              Código Promocional
            </div>
            <form id="promocode-form" action="#">
              <input type="text" name="code" value="#" class="form-control" placeholder="código promoción">
            </form>
            <!--<div class="text-success" id="promocode-success" style="font-size:14px">
              Código aplicado exitosamente
            </div>-->
          </div>
          <!-- END: Promo Detail -->
        </div>
      </div>
    </div>

    <a href="#" class="button" style="margin-top: 20px">Cancelar</a>

  </div>
  <!-- END: S H I P P I N G   A D D R E S S -->

</div>
{% endblock %}