apls/books/urls.py
from django.urls import path

from apls.books import views


app_name = 'book'

urlpatterns = [
    path('', views.book_index, name='index'),
    path('libro/<slug:slug>/', views.detail_view, name='detail'),
]

apls/carts/urls.py
from django.urls import path

from apls.carts import views

app_name = 'cart'

urlpatterns = [
	path('carrito/', views.cart_view, name="detail"),
	path('add_item/', views.add_item_view, name="add_item"),
]

apls/users/urls.py
from django.urls import path

from apls.users import views


app_name = 'users'

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
]

store/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('apls.users.urls')),
    path('', include('apls.books.urls')),
    path('', include('apls.carts.urls')),
    path('', include('apls.orders.urls')),
    path('admin/', admin.site.urls),
]

from django.conf import settings
from django.conf.urls.static import static

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>{% block title %}{% endblock %}</title>
	{% block css %}{% endblock %}
	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
</head>
<body>		
	<nav>
		<a href="#">Book Store</a>
		<div class="nav-menu">
			<a href="{% url 'cart:detail' %}" class="btn">Carrito ({% if pending_cart.qty_items %}{{ pending_cart.qty_items }}{% else %}0{% endif %})</a>
			<a href="{% url 'book:index' %}" class="btn">Libros</a>
			{% if user.is_authenticated %}
			<a href="#" class="btn">Dashboard</a>
			<a href="{% url 'users:logout' %}" class="btn is-link">Salir</a>
			{% else %}	
			<a href="{% url 'users:login' %}" class="btn">Login</a>
			<a href="#" class="btn is-link">Registrar</a>
			{% endif %}
		</div>
	</nav>

	{% block content %}{% endblock %}

	<!--<footer>
		<p>Esto es un footer</p>
	</footer>-->
	

</body>
</html>